### ISSUE TITLE
Delete 2 times when throwing errors out of function.

### ISSUE THREAD

**Issue by ILoveCodeAF** [thangdinh1298/FastHTTPFileDownloader#5]
khi throw lỗi ra khỏi chương trình để test thì có lỗi khi gọi chức năng xóa thì sẽ delete 2 lần (finally của try - catch được gọi 2 lần) 
giải pháp tạm thời không throw lỗi trong catch trong hàm deleteDownload in class DownloadManager.

**Comment by thangdinh1298** [comment]
Đã fix ở commit 3ea9764
